word_act = dict({'normal': 'A state or behavior in everyday life without any special risk or problem.',
'abuse': 'The act of causing physical or mental harm to another person through words or actions, infringing on their rights.',  
'arrest': 'A measure by law enforcement to detain a crime suspect and restrict their freedom.',  
'arson': 'The criminal act of intentionally setting fire to property or life, causing significant damage.',  
'assault': 'The act of inflicting physical violence or harm on another person.',  
'burglary': 'The crime of secretly entering a residence or building to steal property.',  
'explosion': 'A sudden release of energy from pressure or chemical reaction, producing a loud blast and shockwave.',  
'fighting': 'A physical altercation where two or more individuals attack each other with fists, feet, or weapons.',  
'roadAccidents': 'Accidents on roads involving collisions between vehicles, pedestrians, or bicycles.',  
'robbery': 'The act of taking someone’s property by threat or use of force.',  
'shooting': 'The act of firing projectiles from a firearm or other projectile weapon.',
'shoplifting': 'The act of concealing and stealing merchandise from a store.',  
'stealing':' The act of taking someone else’s property without their permission.',
'vandalism': 'The act of willfully damaging or defacing public facilities or another person’s property.'})